In [3]:
#introduction TO numpy


In [2]:
import numpy as np    

In [1]:
 my_list=[1 , 2 , 3 , 4]

In [2]:
my_list

[1, 2, 3, 4]

In [5]:
my_arr= np.array(my_list)

In [6]:
my_arr

array([1, 2, 3, 4])

In [7]:
my_list=[[1 , 2 , 3 , 4],[5 , 6 , 7 , 8],[9 , 10 , 11, 12]]

In [8]:
my_list

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [9]:
my_arr = np.array(my_list)

In [10]:
my_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
arr= np.arange(0,11)

In [12]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
#above creates an array from 0 to n-1

In [14]:
arr = np.arange( 0 , 11 , 2)

In [15]:
arr

array([ 0,  2,  4,  6,  8, 10])

In [16]:
#above creates an array from 0 to 11 with a step size of 2

In [17]:
arr = np.zeros(4)

In [18]:
arr

array([0., 0., 0., 0.])

In [19]:
#above creates an array with 4 zeros

In [21]:
arr = np.zeros((3,3))

In [22]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
# above we have created a two dimentional matrix

In [63]:
arr = np.ones(5)

In [64]:
arr

array([1., 1., 1., 1., 1.])

In [70]:
arr = np.ones((5,5))

In [71]:
arr = np.ones((5,5))

In [72]:
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [67]:
np.ndim(arr)

2

In [68]:
type(arr)

numpy.ndarray

In [33]:
arr

array(42)

In [28]:
arr = np.array(42)

In [29]:
arr

array(42)

In [30]:
type(arr)

numpy.ndarray

In [31]:
# above is an instance of package numpy and class of ndarray nd stands for n dimentional array

In [32]:
np.ndim(arr)

0

In [73]:
# above we see the dimension of arr

In [80]:
arr = np.array((1.1 , 2.3 , 3.5))

In [86]:
arr

array([1.1, 2.3, 3.5])

In [87]:
arr.ndim

1

In [82]:
arr.dtype

dtype('float64')

In [84]:
np.array([ 1, 2 , 3],dtype= 'float64')

array([1., 2., 3.])

In [85]:
# see the documentation for array

In [89]:
np.linspace( 1 , 10 , 4 ) 

array([ 1.,  4.,  7., 10.])

In [90]:
# above we have created an array from 0 to 10 with space between them is even ie.. 3

In [94]:
np.linspace( 0, 1 , 30 , retstep=True )

(array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
        0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
        0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
        0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
        0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
        0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ]),
 0.034482758620689655)

In [97]:
# note that above is a single dimentional array by seeing the paranthesis and the returnstep function gives 
#us the space between each of them

In [89]:
arr = np.linspace( 1, 10 )

In [90]:
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [91]:
arr.shape

(50,)

In [101]:
# shape gives us the number of elements

In [102]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [103]:
# this created a 4 by 4 array we create an identity matrix with floating value

In [3]:
np.eye( 4 ,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [4]:
np.eye( 4 ,k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [5]:
# notice that the mean diagonal shifts by one place

In [6]:
np.random.rand(2)

array([0.7725124 , 0.64343372])

In [8]:
# above takes a number from 0 to 1 and takes from uniform distribution and similarly we can also create 
# multi dimensional array random variables

In [9]:
np.random.rand(5,5)

array([[0.78207623, 0.40562481, 0.22433117, 0.33996154, 0.30802971],
       [0.30266535, 0.21150707, 0.63146066, 0.7893079 , 0.4339565 ],
       [0.0549389 , 0.53351149, 0.6390684 , 0.2978233 , 0.98370533],
       [0.3692291 , 0.87157323, 0.12617298, 0.98189494, 0.56973283],
       [0.18970344, 0.84602574, 0.46048575, 0.6891219 , 0.02164369]])

In [10]:
# above has 5 rows and 5 columns

In [11]:
np.random.randn(2)

array([-0.38998377,  0.84455728])

In [12]:
# above takes random values from standard normal distribution

In [13]:
np.random.randint(0,10)

7

In [14]:
np.random.randint(0,10,10)

array([1, 4, 8, 2, 3, 7, 8, 7, 2, 8])

In [15]:
np.random.randint( 0 , 100 , ( 3,4)) 

array([[ 6, 58, 97, 18],
       [76, 18, 45, 81],
       [49, 13, 87, 36]])

In [16]:
# above creates a multi dimensional array from 0 to 99

In [18]:
np.random.seed(42)
np.random.randint(0,10,5)

array([6, 3, 7, 4, 6])

In [19]:
# above generates the same random number in this cell

In [33]:
rnd_arr= np.random.randint(0,25,25)

In [27]:
rnd_arr

array([15, 14, 14, 18, 11, 22, 19, 24,  2,  4, 18,  6, 20,  8,  6, 17,  3,
       24, 13, 17,  8, 20,  1, 19, 14])

In [37]:
rnd_arr.reshape(5,5)

array([[ 6, 11,  7, 14,  2],
       [13, 16,  3, 17,  7],
       [ 3,  1,  5, 21,  9],
       [ 3, 21, 17, 11,  1],
       [ 9,  3, 13, 15, 14]])

In [39]:
rnd_arr.max()

21

In [30]:
# this reshapes the array into a 2 dimensional array of 5 rows and 5 columns

In [31]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
rnd_arr.max()

21

In [42]:
rnd_arr

array([ 6, 11,  7, 14,  2, 13, 16,  3, 17,  7,  3,  1,  5, 21,  9,  3, 21,
       17, 11,  1,  9,  3, 13, 15, 14])

In [43]:
rnd_arr.argmax()

13

In [44]:
# so the maximum value is at the thirteenth place

In [45]:
my_list = [ 1, 2, 3, 4, 5, 6 , 7, 8, 9]

In [46]:
my_list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [48]:
my_list[0]

1

In [49]:
# indexing

In [50]:
arr = np.arange(20)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [53]:
arr[0]

0

In [54]:
my_list[0:5]

[1, 2, 3, 4, 5]

In [55]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [57]:
my_list[0:10:2]

[1, 3, 5, 7, 9]

In [58]:
# above takes numbers from index 0 to 10 in steps of 2

In [60]:
arr[0:10:2]

array([0, 2, 4, 6, 8])

In [61]:
arr_slice = arr[0:10]

In [62]:
arr_slice[:]=0

In [63]:
arr_slice

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [64]:
arr

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [65]:
# notice that array slice has changed the original too!!

In [66]:
mat = np.arange(0,25).reshape(5,5)

In [67]:
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [68]:
mat[0]

array([0, 1, 2, 3, 4])

In [69]:
# line 0 of the above matrix prints

In [70]:
mat[0][2]

2

In [71]:
mat[:,1]

array([ 1,  6, 11, 16, 21])

In [72]:
# here we get all the rows from first column

In [73]:
mat[:2,:2]

array([[0, 1],
       [5, 6]])

In [74]:
# so we get 2 rows and 2 columns

In [75]:
mat[2:,3:]

array([[13, 14],
       [18, 19],
       [23, 24]])

In [77]:
mat[::2,:]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [78]:
# above took step size of 2 so it skips 1 row after each

In [79]:
mat[2::,:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [80]:
# above took after 2 row and all the columns

In [83]:
mat = np.zeros((10,10))


In [84]:
mat

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [93]:
for i in range (mat.shape[1]):
    mat[i]=i


In [94]:
mat

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [95]:
# above we tahe shape of mat as a 1 dimensional array ie.. 10 so it runs from 0 to 10 and each row
# gets assigned with i value and next time the loop increments

In [96]:
mat[[ 1 , 3 , 5 , 6 ]]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]])

In [99]:
# it takes the index

In [101]:
arr = np.arange(0,10)

In [102]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
arr > 2

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [104]:
# it actually creates a booleaN MASK for the values greater than 2

In [105]:
filter = arr > 3

In [106]:
arr[filter]

array([4, 5, 6, 7, 8, 9])

In [109]:
arr = np.arange(0,11)

In [110]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [108]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [111]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [112]:
# power of 2

In [113]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [114]:
arr -arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [115]:
arr / arr

/srv/conda/envs/notebook/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [116]:
# 0/0 not a number

In [117]:
 1/ arr

/srv/conda/envs/notebook/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

universal functions

In [118]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [119]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [120]:
np.square(arr)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [121]:
np.log(arr)

/srv/conda/envs/notebook/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [122]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [123]:
np.max(arr)

10

In [124]:
np.min(arr)

0

In [125]:
mat_1 = np.array([[ 1, 2, 3 , 4 ],[ 5 , 6 , 7 , 8]])

In [137]:
mat_2 = np.array([[ 9, 10 , 11 , 12], [ 13 , 14 , 15 , 16]])

In [138]:
mat_1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [127]:
mat_1 +mat_2

array([[10, 12, 14, 16],
       [18, 20, 22, 24]])

In [128]:
np.add(mat_1,mat_2)

array([[10, 12, 14, 16],
       [18, 20, 22, 24]])

In [130]:
np.subtract(mat_1,mat_2)

array([[-8, -8, -8, -8],
       [-8, -8, -8, -8]])

In [131]:
np.divide(mat_1,mat_2)

array([[0.11111111, 0.2       , 0.27272727, 0.33333333],
       [0.38461538, 0.42857143, 0.46666667, 0.5       ]])

In [132]:
np.multiply(mat_1,mat_2)

array([[  9,  20,  33,  48],
       [ 65,  84, 105, 128]])

In [133]:
np.sum(mat_1)

36

In [135]:
np.sum(mat_1, axis=0)

array([ 6,  8, 10, 12])

In [136]:
np.sum (mat_1,axis=1)

array([10, 26])

In [139]:
# axis=0 sum for columns and axis=1 for rows

In [141]:
v = np.array([9,10])
w = np.array([8,7])

In [142]:
v.dot(w)

142

In [143]:
np.dot(v,w)

142

In [144]:
mat_1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [145]:
mat_1.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [146]:
# transpose