In [3]:
#introduction TO numpy


In [4]:
import numpy as np    

In [1]:
 my_list=[1 , 2 , 3 , 4]

In [2]:
my_list

[1, 2, 3, 4]

In [5]:
my_arr= np.array(my_list)

In [6]:
my_arr

array([1, 2, 3, 4])

In [7]:
my_list=[[1 , 2 , 3 , 4],[5 , 6 , 7 , 8],[9 , 10 , 11, 12]]

In [8]:
my_list

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [9]:
my_arr = np.array(my_list)

In [10]:
my_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
arr= np.arange(0,11)

In [12]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
#above creates an array from 0 to n-1

In [14]:
arr = np.arange( 0 , 11 , 2)

In [15]:
arr

array([ 0,  2,  4,  6,  8, 10])

In [16]:
#above creates an array from 0 to 11 with a step size of 2

In [17]:
arr = np.zeros(4)

In [18]:
arr

array([0., 0., 0., 0.])

In [19]:
#above creates an array with 4 zeros

In [21]:
arr = np.zeros((3,3))

In [22]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
# above we have created a two dimentional matrix

In [63]:
arr = np.ones(5)

In [64]:
arr

array([1., 1., 1., 1., 1.])

In [70]:
arr = np.ones((5,5))

In [71]:
arr = np.ones((5,5))

In [72]:
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [67]:
np.ndim(arr)

2

In [68]:
type(arr)

numpy.ndarray

In [33]:
arr

array(42)

In [28]:
arr = np.array(42)

In [29]:
arr

array(42)

In [30]:
type(arr)

numpy.ndarray

In [31]:
# above is an instance of package numpy and class of ndarray nd stands for n dimentional array

In [32]:
np.ndim(arr)

0

In [73]:
# above we see the dimension of arr

In [80]:
arr = np.array((1.1 , 2.3 , 3.5))

In [86]:
arr

array([1.1, 2.3, 3.5])

In [87]:
arr.ndim

1

In [82]:
arr.dtype

dtype('float64')

In [84]:
np.array([ 1, 2 , 3],dtype= 'float64')

array([1., 2., 3.])

In [85]:
# see the documentation for array

In [89]:
np.linspace( 1 , 10 , 4 ) 

array([ 1.,  4.,  7., 10.])

In [90]:
# above we have created an array from 0 to 10 with space between them is even ie.. 3

In [94]:
np.linspace( 0, 1 , 30 , retstep=True )

(array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
        0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
        0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
        0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
        0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
        0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ]),
 0.034482758620689655)

In [97]:
# note that above is a single dimentional array by seeing the paranthesis and the returnstep function gives 
#us the space between each of them

In [98]:
arr = np.linspace( 1, 10 )

In [99]:
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [100]:
arr.shape

(50,)

In [101]:
# shape gives us the number of elements

In [102]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [103]:
# this created a 4 by 4 array we create an identity matrix with floating value